version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      context: ./packages/nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./packages/client/:/app
  api:
    depends_on:
      - postgres
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./packages/server/:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    build:
      context: ./packages/worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./packages/worker/:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379