version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./packages/client/:/app
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./packages/server/:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=54
  worker:
    build:
      context: ./packages/worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./packages/worker/:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379